{
 "title": "Phone-Book-CRUD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"dev-fest-crud\"})"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"dev-fest-crud\"})"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"dev-fest-crud\"})"
    }
   ]
  },
  {
   "title": "File Discriptors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(process_open_fds{job=\"dev-fest-crud\"}/ process_max_fds{job=\"dev-fest-crud\"}) * 100"
    }
   ]
  },
  { "title": "Request Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_sum[1m])/rate(dev_fest_phone_book_crud_request_latency_count[1m])"
    }
   ]
  },
  { "title": "Request Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(dev_fest_phone_book_crud_request_latency_count[1m]))"
    }
   ]
  },
  {
   "title": "POST",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count{method=\"post\"}[1m])"
    }
   ]
  },
  {
   "title": "GET",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count{method=\"get\"}[1m])"
    }
   ]
  },
  {
   "title": "GET-ALL",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count{method=\"get_all\"}[1m])"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count{method=\"put\"}[1m])"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dev_fest_phone_book_crud_request_latency_count{method=\"delete\"}[1m])"
    }
   ]
  },
  { "title": "Runtime Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"dev-fest-crud\"}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=~\"dev-fest-crud\"}/ go_gc_duration_seconds_count{job=~\"dev-fest-crud\"}"
    }
   ]
  },
  {
   "title": "File Discriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{job=\"dev-fest-crud\"}/ process_max_fds{job=\"dev-fest-crud\"})*100"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"dev-fest-crud\"}"
    }
   ]
  }
 ]
}